[book]
authors = [
    "An-I Yu <mellivorandy@gmail.com>"
]
description = "A general-purpose guide for mmWave radar applications."
language = "en"
# multilingual = true
src = "src"
title = "mmWave Handbook"
edition = "2025"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/mellivorandy/mmwave-handbook"
git-repository-icon = "fa-github"
site-url = "https://mellivorandy.github.io/mmwave-handbook/"